# Generated by Django 4.1.7 on 2023-07-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_DTB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_category',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('REPAIR', 'REPAIR'), ('PRINTER', 'PRINTER'), ('CLEANING', 'CLEANING'), ('OTHER', 'OTHER')], max_length=50),
        ),
    ]
